<a href="https://colab.research.google.com/github/oshmita26/Pytorch_mini_projects/blob/tutorials/Tutorials/Pytorch_tutorial_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install torch torchvision

  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
  Using cached nvidia_nvjitlink_cu12-12.4.127-py3-none-m

In [4]:
import torch
import torchvision

In [5]:
print(torch.cuda.is_available())

True


In [6]:
print(torch.__version__)

2.2.1+cu121


In [9]:
torch.cuda.get_device_name(0)

'Tesla T4'

Working with numpy and tensors

In [10]:
import numpy as np
lst = [3, 5, 6]
arr = np.array(lst)
arr

array([3, 5, 6])

In [12]:
arr.dtype

dtype('int64')

In [14]:
## Converting numpy to pytorch tensors
tensors = torch.from_numpy(arr)
tensors

tensor([3, 5, 6])

In [15]:
## Indexing similar to numpy
tensors[:2]

tensor([3, 5])

In [17]:
tensors.dtype

torch.int64

In [18]:
## Prevent this by using torch.tensor
tensor_arr = torch.tensor(arr)
tensor_arr

tensor([3, 5, 6])

In [20]:
## Does not use the same memory space
tensor_arr[2] = 120
print(arr)
print(tensor_arr)

[3 5 6]
tensor([  3,   5, 120])


In [22]:
## zeroes and ones
torch.zeros(2, 3, dtype=torch.float64) ## Matrix dimensions

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [23]:
torch.ones(2, 3, dtype=torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [27]:
a = torch.tensor(np.arange(0, 15).reshape(5, 3)) ## If it's not a multiple there will be a problem in the reshaping of the array
a

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

## Arithmetic operations

In [28]:
a = torch.tensor([1, 2, 3], dtype=torch.float)
b = torch.tensor([3, 4, 5], dtype=torch.float)
print(a+b)

tensor([4., 6., 8.])


In [29]:
c = torch.zeros(3)
torch.add(a, b, out=c) ## Addition a + b and the output is stored in c

tensor([4., 6., 8.])

In [30]:
c

tensor([4., 6., 8.])

In [31]:
ans = torch.add(a, b).sum()
ans

tensor(18.)

In [32]:
## normal multiplication
a.mul(b)

tensor([ 3.,  8., 15.])

In [33]:
## Dot product
a.dot(b)

tensor(26.)

In [35]:
## matrix multiplication
x = torch.tensor([[1, 4, 2], [1, 5, 5]], dtype=torch.float)
y = torch.tensor([[5, 7], [8, 6], [9, 1]], dtype=torch.float)
torch.matmul(x, y)

tensor([[55., 33.],
        [90., 42.]])

In [36]:
## Another way of doing it
torch.mm(x, y)

tensor([[55., 33.],
        [90., 42.]])